export const SET_ACTIVE_STEP = 'SET_ACTIVE_STEP'
export const SAVE_STEP_1 = 'SAVE_STEP_1'
export const SAVE_STEP_2 = 'SAVE_STEP_2'
export const SUBMIT_FORM = 'SUBMIT_FORM'
export const SUBMIT_FORM_DONE = 'SUBMIT_FORM_DONE'
export const SUBMIT_FORM_ERROR = 'SUBMIT_FORM_ERROR'
export const RESET_FORM = 'RESET'
